### ISSUE TITLE
Bug in pythonpackage.yaml in the blog post

### ISSUE THREAD

**Issue by parautenbach** [boralyl/github-custom-component-tutorial#1]
I've found your two posts super useful. Thank you for taking the time to do this write-up!

As I first-time contributor to the Home Assistant project and being new to GitHub Actions I got stuck on the testing section of the [2nd post](https://aarongodfrey.dev/home%20automation/building_a_home_assistant_custom_component_part_2/).

I see the correct `pythonpackage.yaml` is in the repo (I didn't think about looking at the repo until after I figured out what the problem was). I thought `$` was some kind of shorthand and struggled to find anything about it in the GitHub Actions docs but found the appropriate syntax reading the docs for that [specific action](https://github.com/actions/setup-python). 

This is the problematic section:
```
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python $
        uses: actions/setup-python@v1
        with:
          python-version: $
```

Would it be possible to amend the blog post?
